-- ripgrep (with pcre2 feature) should be installed on your system and added to path

require "plugin-manager"
require "set"
require "keymap"
require "autocmd"
require "plugins.colorschemes.vscode"
require "plugins.lsp"
require "plugins.treesitter"
require "plugins.dap"
require "plugins.telescope"
require "plugins.lualine"
require "plugins.bufferline"
require "plugins.startify"
require "plugins.neotree"
require "plugins.illuminate"
require "plugins.neoscroll"
-- require "plugins.scrollbar" -- The culprit of an extremely slow performance
require "plugins.Comment"
require "plugins.windows"
require "plugins.ufo"
require "plugins.gitui"
require "plugins.diffview"
require "plugins.ccc"
